### ISSUE TITLE
Line breaks being removed

### ISSUE THREAD

**Issue by philefstat** [lsdsjy/prettier-plugin-stylus#4]
First of, thanks for creating this package - it's great to finally have a plugin for stylus. 

A question: is there some way to preserve line breaks and / or colons. In particular line breaks, as I think they help a lot with readability. Here's an example before/after: 

<img width="324" alt="Screenshot 2022-07-29 at 16 25 32" src="https://user-images.githubusercontent.com/9018494/181793066-52fd419f-e297-4fd8-b1b6-17eeb4f2f14d.png">
<img width="297" alt="Screenshot 2022-07-29 at 16 25 38" src="https://user-images.githubusercontent.com/9018494/181793079-348d2ff2-9305-43b6-b379-eb34096998e3.png">

Again, thanks very much for creating this!

**Comment by lsdsjy** [comment]
Colons are now by default omitted, because Stylus embraces what's called "pythonic" style. Maybe later I can add an option to prefer colons and semicolons.
Preserving line breaks is important but now Stylus parser just ignores whitespaces. I'll try to look into it.

**Comment by lsdsjy** [comment]
I think it's solved in 0.0.1-beta.4. Welcome to try it and share your feedback!

**Comment by philefstat** [comment]
@lsdsjy Thanks very much for your quick response. Having an option to prefer colons would be much appreciated, but I understand 😄 Maybe if I can find the time I'll have a look at how to do that and make a PR. 

I tested 0.0.4 (by pulling locally - don't think the npm package has been published yet) and am still seeing some weird behaviour with spacing, though it seems to be working in some files. For context these are all vue SFCs.


<img width="420" alt="Screenshot 2022-07-30 at 13 57 29" src="https://user-images.githubusercontent.com/9018494/181915438-56b6f15f-294a-4714-81d5-3d13c5ae3c56.png">
<img width="320" alt="Screenshot 2022-07-30 at 13 57 15" src="https://user-images.githubusercontent.com/9018494/181915440-42db4836-d352-4943-84e0-aa486990fb76.png">

**Comment by lsdsjy** [comment]
Sorry I forgot to publish the package. 😅
I think I should add some test cases for Vue SFC. I'll investigate into it.

**Comment by lsdsjy** [comment]
I've added a test case for Vue SFC and it seems blank lines are preserved as expected(See https://github.com/lsdsjy/prettier-plugin-stylus/commit/87f22b41c3cf7b1a907cb9c37e4cf53c28e56500). Can you install v0.0.1-beta.4 from npm and try again? If it still doesn't work, can you provide a minimal reproduction then?

**Comment by philefstat** [comment]
Yep works now, thanks very much!

Though I've spotted another issue: On every save, a new line break is added to the start of the <style> tag. In other words, after 5 saves, it looks like this:

<img width="413" alt="Screenshot 2022-08-01 at 16 40 13" src="https://user-images.githubusercontent.com/9018494/182187092-5faf7e5b-0055-4701-9661-03d25f8f82fc.png">

**Comment by lsdsjy** [comment]
It's caused by several factors:
1. Prettier slice the string right after `<style>` tag as the input to the corresponding style prettier plugin, for example:
```vue
<style lang="stylus">
.a
  color white
</style>
```
Plugin receives the source code as: `"\n.a\n..."`(note the leading \n here).

2. Prettier always add a `\n` after the `<style>` tag if it is not empty(which applies to `<template>` and `<script>` too), for example:
```vue
<style>.a {  color: white; }
</style>
```
would become:
```vue
<style>
.a {  color: white; }
</style>
```

3. *This* plugin preserves all blank lines(i.e. `\n`s).

So there would be two and more blank lines if you prettier the file multiple times.

I played with the prettier css plugin and found: it always trims the blank lines on the beginning and end; and preserves only one blank lines in between. I think we should respect that behavior too. Any thoughts?

**Comment by lsdsjy** [comment]
Fixed in prettier-plugin-stylus@0.0.1-beta.6. However we still preserve consecutive blank lines in between for now, which I think is a great feature to have.
